package com.iustu.agent.dubbo.model;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/AgentRequestProto.proto

public final class AgentRequestProto {
    private AgentRequestProto() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface AgentRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:AgentRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>int64 id = 1;</code>
         */
        long getId();

        /**
         * <code>string interfaceName = 2;</code>
         */
        java.lang.String getInterfaceName();

        /**
         * <code>string interfaceName = 2;</code>
         */
        com.google.protobuf.ByteString
        getInterfaceNameBytes();

        /**
         * <code>string method = 3;</code>
         */
        java.lang.String getMethod();

        /**
         * <code>string method = 3;</code>
         */
        com.google.protobuf.ByteString
        getMethodBytes();

        /**
         * <code>string parameterTypesString = 4;</code>
         */
        java.lang.String getParameterTypesString();

        /**
         * <code>string parameterTypesString = 4;</code>
         */
        com.google.protobuf.ByteString
        getParameterTypesStringBytes();

        /**
         * <code>string parameter = 5;</code>
         */
        java.lang.String getParameter();

        /**
         * <code>string parameter = 5;</code>
         */
        com.google.protobuf.ByteString
        getParameterBytes();
    }

    /**
     * Protobuf type {@code AgentRequest}
     */
    public static final class AgentRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:AgentRequest)
            AgentRequestOrBuilder {
        private static final long serialVersionUID = 0L;

        // Use AgentRequest.newBuilder() to construct.
        private AgentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private AgentRequest() {
            id_ = 0L;
            interfaceName_ = "";
            method_ = "";
            parameterTypesString_ = "";
            parameter_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        private AgentRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!parseUnknownFieldProto3(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            id_ = input.readInt64();
                            break;
                        }
                        case 18: {
                            java.lang.String s = input.readStringRequireUtf8();

                            interfaceName_ = s;
                            break;
                        }
                        case 26: {
                            java.lang.String s = input.readStringRequireUtf8();

                            method_ = s;
                            break;
                        }
                        case 34: {
                            java.lang.String s = input.readStringRequireUtf8();

                            parameterTypesString_ = s;
                            break;
                        }
                        case 42: {
                            java.lang.String s = input.readStringRequireUtf8();

                            parameter_ = s;
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return AgentRequestProto.internal_static_AgentRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return AgentRequestProto.internal_static_AgentRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            AgentRequestProto.AgentRequest.class, AgentRequestProto.AgentRequest.Builder.class);
        }

        public static final int ID_FIELD_NUMBER = 1;
        private long id_;

        /**
         * <code>int64 id = 1;</code>
         */
        public long getId() {
            return id_;
        }

        public static final int INTERFACENAME_FIELD_NUMBER = 2;
        private volatile java.lang.Object interfaceName_;

        /**
         * <code>string interfaceName = 2;</code>
         */
        public java.lang.String getInterfaceName() {
            java.lang.Object ref = interfaceName_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                interfaceName_ = s;
                return s;
            }
        }

        /**
         * <code>string interfaceName = 2;</code>
         */
        public com.google.protobuf.ByteString
        getInterfaceNameBytes() {
            java.lang.Object ref = interfaceName_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                interfaceName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int METHOD_FIELD_NUMBER = 3;
        private volatile java.lang.Object method_;

        /**
         * <code>string method = 3;</code>
         */
        public java.lang.String getMethod() {
            java.lang.Object ref = method_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                method_ = s;
                return s;
            }
        }

        /**
         * <code>string method = 3;</code>
         */
        public com.google.protobuf.ByteString
        getMethodBytes() {
            java.lang.Object ref = method_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                method_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PARAMETERTYPESSTRING_FIELD_NUMBER = 4;
        private volatile java.lang.Object parameterTypesString_;

        /**
         * <code>string parameterTypesString = 4;</code>
         */
        public java.lang.String getParameterTypesString() {
            java.lang.Object ref = parameterTypesString_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                parameterTypesString_ = s;
                return s;
            }
        }

        /**
         * <code>string parameterTypesString = 4;</code>
         */
        public com.google.protobuf.ByteString
        getParameterTypesStringBytes() {
            java.lang.Object ref = parameterTypesString_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                parameterTypesString_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PARAMETER_FIELD_NUMBER = 5;
        private volatile java.lang.Object parameter_;

        /**
         * <code>string parameter = 5;</code>
         */
        public java.lang.String getParameter() {
            java.lang.Object ref = parameter_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                parameter_ = s;
                return s;
            }
        }

        /**
         * <code>string parameter = 5;</code>
         */
        public com.google.protobuf.ByteString
        getParameterBytes() {
            java.lang.Object ref = parameter_;
            if (ref instanceof java.lang.String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                parameter_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (id_ != 0L) {
                output.writeInt64(1, id_);
            }
            if (!getInterfaceNameBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 2, interfaceName_);
            }
            if (!getMethodBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 3, method_);
            }
            if (!getParameterTypesStringBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 4, parameterTypesString_);
            }
            if (!getParameterBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 5, parameter_);
            }
            unknownFields.writeTo(output);
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (id_ != 0L) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt64Size(1, id_);
            }
            if (!getInterfaceNameBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, interfaceName_);
            }
            if (!getMethodBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, method_);
            }
            if (!getParameterTypesStringBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, parameterTypesString_);
            }
            if (!getParameterBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, parameter_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof AgentRequestProto.AgentRequest)) {
                return super.equals(obj);
            }
            AgentRequestProto.AgentRequest other = (AgentRequestProto.AgentRequest) obj;

            boolean result = true;
            result = result && (getId()
                    == other.getId());
            result = result && getInterfaceName()
                    .equals(other.getInterfaceName());
            result = result && getMethod()
                    .equals(other.getMethod());
            result = result && getParameterTypesString()
                    .equals(other.getParameterTypesString());
            result = result && getParameter()
                    .equals(other.getParameter());
            result = result && unknownFields.equals(other.unknownFields);
            return result;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + ID_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                    getId());
            hash = (37 * hash) + INTERFACENAME_FIELD_NUMBER;
            hash = (53 * hash) + getInterfaceName().hashCode();
            hash = (37 * hash) + METHOD_FIELD_NUMBER;
            hash = (53 * hash) + getMethod().hashCode();
            hash = (37 * hash) + PARAMETERTYPESSTRING_FIELD_NUMBER;
            hash = (53 * hash) + getParameterTypesString().hashCode();
            hash = (37 * hash) + PARAMETER_FIELD_NUMBER;
            hash = (53 * hash) + getParameter().hashCode();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static AgentRequestProto.AgentRequest parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static AgentRequestProto.AgentRequest parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static AgentRequestProto.AgentRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static AgentRequestProto.AgentRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static AgentRequestProto.AgentRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static AgentRequestProto.AgentRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static AgentRequestProto.AgentRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static AgentRequestProto.AgentRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static AgentRequestProto.AgentRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static AgentRequestProto.AgentRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static AgentRequestProto.AgentRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static AgentRequestProto.AgentRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(AgentRequestProto.AgentRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code AgentRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:AgentRequest)
                AgentRequestProto.AgentRequestOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return AgentRequestProto.internal_static_AgentRequest_descriptor;
            }

            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return AgentRequestProto.internal_static_AgentRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                AgentRequestProto.AgentRequest.class, AgentRequestProto.AgentRequest.Builder.class);
            }

            // Construct using AgentRequestProto.AgentRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                id_ = 0L;

                interfaceName_ = "";

                method_ = "";

                parameterTypesString_ = "";

                parameter_ = "";

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return AgentRequestProto.internal_static_AgentRequest_descriptor;
            }

            public AgentRequestProto.AgentRequest getDefaultInstanceForType() {
                return AgentRequestProto.AgentRequest.getDefaultInstance();
            }

            public AgentRequestProto.AgentRequest build() {
                AgentRequestProto.AgentRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public AgentRequestProto.AgentRequest buildPartial() {
                AgentRequestProto.AgentRequest result = new AgentRequestProto.AgentRequest(this);
                result.id_ = id_;
                result.interfaceName_ = interfaceName_;
                result.method_ = method_;
                result.parameterTypesString_ = parameterTypesString_;
                result.parameter_ = parameter_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof AgentRequestProto.AgentRequest) {
                    return mergeFrom((AgentRequestProto.AgentRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(AgentRequestProto.AgentRequest other) {
                if (other == AgentRequestProto.AgentRequest.getDefaultInstance()) return this;
                if (other.getId() != 0L) {
                    setId(other.getId());
                }
                if (!other.getInterfaceName().isEmpty()) {
                    interfaceName_ = other.interfaceName_;
                    onChanged();
                }
                if (!other.getMethod().isEmpty()) {
                    method_ = other.method_;
                    onChanged();
                }
                if (!other.getParameterTypesString().isEmpty()) {
                    parameterTypesString_ = other.parameterTypesString_;
                    onChanged();
                }
                if (!other.getParameter().isEmpty()) {
                    parameter_ = other.parameter_;
                    onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                AgentRequestProto.AgentRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (AgentRequestProto.AgentRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private long id_;

            /**
             * <code>int64 id = 1;</code>
             */
            public long getId() {
                return id_;
            }

            /**
             * <code>int64 id = 1;</code>
             */
            public Builder setId(long value) {

                id_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int64 id = 1;</code>
             */
            public Builder clearId() {

                id_ = 0L;
                onChanged();
                return this;
            }

            private java.lang.Object interfaceName_ = "";

            /**
             * <code>string interfaceName = 2;</code>
             */
            public java.lang.String getInterfaceName() {
                java.lang.Object ref = interfaceName_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    interfaceName_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string interfaceName = 2;</code>
             */
            public com.google.protobuf.ByteString
            getInterfaceNameBytes() {
                java.lang.Object ref = interfaceName_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    interfaceName_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string interfaceName = 2;</code>
             */
            public Builder setInterfaceName(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                interfaceName_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string interfaceName = 2;</code>
             */
            public Builder clearInterfaceName() {

                interfaceName_ = getDefaultInstance().getInterfaceName();
                onChanged();
                return this;
            }

            /**
             * <code>string interfaceName = 2;</code>
             */
            public Builder setInterfaceNameBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                interfaceName_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object method_ = "";

            /**
             * <code>string method = 3;</code>
             */
            public java.lang.String getMethod() {
                java.lang.Object ref = method_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    method_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string method = 3;</code>
             */
            public com.google.protobuf.ByteString
            getMethodBytes() {
                java.lang.Object ref = method_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    method_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string method = 3;</code>
             */
            public Builder setMethod(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                method_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string method = 3;</code>
             */
            public Builder clearMethod() {

                method_ = getDefaultInstance().getMethod();
                onChanged();
                return this;
            }

            /**
             * <code>string method = 3;</code>
             */
            public Builder setMethodBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                method_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object parameterTypesString_ = "";

            /**
             * <code>string parameterTypesString = 4;</code>
             */
            public java.lang.String getParameterTypesString() {
                java.lang.Object ref = parameterTypesString_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    parameterTypesString_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string parameterTypesString = 4;</code>
             */
            public com.google.protobuf.ByteString
            getParameterTypesStringBytes() {
                java.lang.Object ref = parameterTypesString_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    parameterTypesString_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string parameterTypesString = 4;</code>
             */
            public Builder setParameterTypesString(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                parameterTypesString_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string parameterTypesString = 4;</code>
             */
            public Builder clearParameterTypesString() {

                parameterTypesString_ = getDefaultInstance().getParameterTypesString();
                onChanged();
                return this;
            }

            /**
             * <code>string parameterTypesString = 4;</code>
             */
            public Builder setParameterTypesStringBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                parameterTypesString_ = value;
                onChanged();
                return this;
            }

            private java.lang.Object parameter_ = "";

            /**
             * <code>string parameter = 5;</code>
             */
            public java.lang.String getParameter() {
                java.lang.Object ref = parameter_;
                if (!(ref instanceof java.lang.String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    java.lang.String s = bs.toStringUtf8();
                    parameter_ = s;
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>string parameter = 5;</code>
             */
            public com.google.protobuf.ByteString
            getParameterBytes() {
                java.lang.Object ref = parameter_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (java.lang.String) ref);
                    parameter_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string parameter = 5;</code>
             */
            public Builder setParameter(
                    java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                parameter_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string parameter = 5;</code>
             */
            public Builder clearParameter() {

                parameter_ = getDefaultInstance().getParameter();
                onChanged();
                return this;
            }

            /**
             * <code>string parameter = 5;</code>
             */
            public Builder setParameterBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                parameter_ = value;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFieldsProto3(unknownFields);
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:AgentRequest)
        }

        // @@protoc_insertion_point(class_scope:AgentRequest)
        private static final AgentRequestProto.AgentRequest DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new AgentRequestProto.AgentRequest();
        }

        public static AgentRequestProto.AgentRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<AgentRequest>
                PARSER = new com.google.protobuf.AbstractParser<AgentRequest>() {
            public AgentRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new AgentRequest(input, extensionRegistry);
            }
        };

        public static com.google.protobuf.Parser<AgentRequest> parser() {
            return PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<AgentRequest> getParserForType() {
            return PARSER;
        }

        public AgentRequestProto.AgentRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_AgentRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_AgentRequest_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n0src/main/resources/proto/AgentRequestP" +
                        "roto.proto\"r\n\014AgentRequest\022\n\n\002id\030\001 \001(\003\022\025" +
                        "\n\rinterfaceName\030\002 \001(\t\022\016\n\006method\030\003 \001(\t\022\034\n" +
                        "\024parameterTypesString\030\004 \001(\t\022\021\n\tparameter" +
                        "\030\005 \001(\tB\023B\021AgentRequestProtob\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_AgentRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_AgentRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_AgentRequest_descriptor,
                new java.lang.String[]{"Id", "InterfaceName", "Method", "ParameterTypesString", "Parameter",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
